services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./backend:/app/src

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.dev
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true
